version: '3.1'
name: agave
services:
  frontend:
    build:
      context: frontend
      target: development
    env_file:
       - .env
    networks:
      - client-side
    ports:
      - 3000:3000
    volumes:
      - ./frontend/src:/app/src

  backend:
    build:
      context: backend
      target: development
    env_file:
       - .env
    networks:
      - client-side
      - server-side
    ports:
      - 8000:8000
    volumes:
      - ./backend/src:/app/src
      - backend-cache:/app/target
    depends_on:
      - db

  db:
    image: postgres:12-alpine
    restart: always
    env_file:
       - .env
    environment:
      POSTGRES_PASSWORD: ${PG_PASSWORD}
    networks:
      - server-side
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data

networks:
  client-side: {}
  server-side: {}

volumes:
  backend-cache: {}
  db-data: {}
