FROM rust:1.79-alpine

WORKDIR /api
RUN apk add --no-cache musl-dev \ 
    && cargo install cargo-watch
COPY ./ ./
RUN cargo build

EXPOSE 8000

# CMD ["sh", "-c", "cargo watch -q -c x run"]
CMD ["echo", "hello world!"]